# Generated by Django 4.1.7 on 2023-02-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='habits',
        ),
        migrations.AddField(
            model_name='habit',
            name='days',
            field=models.ManyToManyField(to='core.day'),
        ),
    ]
