# Generated by Django 4.1.7 on 2023-02-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_day_habits_habit_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='habits',
            field=models.ManyToManyField(to='core.habit'),
        ),
        migrations.AlterField(
            model_name='habitweekday',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
