# Generated by Django 4.1.7 on 2023-02-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_day_habits_habit_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='habits',
            field=models.ManyToManyField(related_name='days', to='core.habit'),
        ),
        migrations.AlterField(
            model_name='habitweekday',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitweekdays', to='core.habit'),
        ),
        migrations.AlterField(
            model_name='habitweekday',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
